// MSBTE K15 faculty evaluation questions — order matches Firestore score indices (0–15).
export const FEEDBACK_QUESTIONS = [
  "Coverage of syllabus",
  "Covering relevant topics beyond the syllabus",
  "Effectiveness in terms of technical contents / course contents",
  "Effectiveness in terms of communication skills",
  "Effectiveness in terms of Teaching aids",
  "Motivation and inspiration for students to learn in self-learning mode",
  "Support for development of student skills: Practical Performance",
  "Support for development of student skills: Project and Seminar preparation",
  "Feedback provided on student progress",
  "Punctuality and discipline",
  "Domain Knowledge",
  "Interaction with students",
  "Ability to resolve difficulties",
  "Encourage to participate in cocurricular activities",
  "Encourage to participate in Extracurricular activities",
  "Guidance during Internship",
];

export const INSTITUTION_QUESTIONS = [
  "Availability of magazines & journals in library",
  "Availability of reference books in library",
  "Available reading space in the library",
  "Cooperation of library staff",
  "Availability of reprographic (xerox) facility",
  "Office administration & governance",
  "Help for applying scholarship & forwarding documents",
  "Receipt of documents like marksheets, halltickets, bonafide, etc. in time",
  "Overall academic satisfaction for classroom teaching",
  "Overall academic satisfaction for laboratory works",
  "Classroom facilities",
  "Laboratory facilities",
  "College level examination conduct & evaluation",
  "Board level examination conduct & evaluation",
  "Satisfaction on project work",
  "Overall discipline in the college",
  "Ecofriendly atmosphere in campus",
  "Sanitation & cleanliness of college premises",
  "Computer & internet facilities",
  "Training & placement activity",
  "Mentoring (parent-teacher) concept",
  "Cocurricular & extra curricular activites like arrangement of guest lectures, visits, workshops",
  "Career guidance",
  "Transport facility",
  "Canteen facility",
  "Drinking water facility",
];
